import { excl } from "@d-exclaimation/next";

export const all = excl("items", () => [
  {
    name: "bowl",
    icon: "🥣",
    category: "Utensil",
    difficulty: 2,
  },
  {
    name: "spoon",
    icon: "🥄",
    category: "Utensil",
    difficulty: 2,
  },
  {
    name: "knife",
    icon: "🔪",
    category: "Utensil",
    difficulty: 3,
  },
  {
    name: "cup",
    icon: "🥤",
    category: "Beverage",
    difficulty: 1,
  },
  {
    name: "wine glass",
    icon: "🍷",
    category: "Beverage",
    difficulty: 4,
  },
  {
    name: "bottle",
    icon: "🍾",
    category: "Beverage",
    difficulty: 1,
  },
  {
    name: "cake",
    icon: "🎂",
    category: "Food",
    difficulty: 3,
  },
  {
    name: "donut",
    icon: "🍩",
    category: "Food",
    difficulty: 2,
  },
  {
    name: "pizza",
    icon: "🍕",
    category: "Food",
    difficulty: 2,
  },
  {
    name: "hot dog",
    icon: "🌭",
    category: "Food",
    difficulty: 2,
  },
  {
    name: "sandwich",
    icon: "🥪",
    category: "Food",
    difficulty: 2,
  },
  {
    name: "carrot",
    icon: "🥕",
    category: "Groceries",
    difficulty: 2,
  },
  {
    name: "broccoli",
    icon: "🥦",
    category: "Groceries",
    difficulty: 2,
  },
  {
    name: "orange",
    icon: "🍊",
    category: "Groceries",
    difficulty: 2,
  },
  {
    name: "apple",
    icon: "🍎",
    category: "Groceries",
    difficulty: 2,
  },
  {
    name: "banana",
    icon: "🍌",
    category: "Groceries",
    difficulty: 2,
  },
  {
    name: "surfboard",
    icon: "🏄‍♂️",
    category: "Sport Gear",
    difficulty: 6,
  },
  {
    name: "skateboard",
    icon: "🛹",
    category: "Sport Gear",
    difficulty: 2,
  },
  {
    name: "snowboard",
    icon: "🏂",
    category: "Sport Gear",
    difficulty: 6,
  },
  {
    name: "skis",
    icon: "🎿",
    category: "Sport Gear",
    difficulty: 4,
  },
  {
    name: "kite",
    icon: "🪁",
    category: "Sport Object",
    difficulty: 7,
  },
  {
    name: "sports ball",
    icon: "⚽",
    category: "Sport Object",
    difficulty: 2,
  },
  {
    name: "frisbee",
    icon: "🥏",
    category: "Sport Object",
    difficulty: 3,
  },
  {
    name: "phone",
    icon: "📱",
    category: "Electronics",
    difficulty: 1,
  },
  {
    name: "keyboard",
    icon: "⌨️",
    category: "Electronics",
    difficulty: 1,
  },
  {
    name: "mouse",
    icon: "🖱️",
    category: "Electronics",
    difficulty: 1,
  },
  {
    name: "laptop",
    icon: "💻",
    category: "Electronics",
    difficulty: 1,
  },
  {
    name: "tvmonitor",
    icon: "📺",
    category: "Electronics",
    difficulty: 1,
  },
  {
    name: "toothbrush",
    icon: "🪥",
    category: "Small Object",
    difficulty: 3,
  },
  {
    name: "teddy bear",
    icon: "🧸",
    category: "Small Object",
    difficulty: 5,
  },
  {
    name: "scissors",
    icon: "✂️",
    category: "Small Object",
    difficulty: 2,
  },
  {
    name: "clock",
    icon: "🕰️",
    category: "Small Object",
    difficulty: 3,
  },
  {
    name: "book",
    icon: "📚",
    category: "Small Object",
    difficulty: 1,
  },
  {
    name: "chair",
    icon: "🪑",
    category: "Public Object",
    difficulty: 2,
  },
  {
    name: "traffic light",
    icon: "🚦",
    category: "Public Object",
    difficulty: 5,
  },
  {
    name: "vase",
    icon: "🏺",
    category: "House Object",
    difficulty: 2,
  },
  {
    name: "pottedplant",
    icon: "🪴",
    category: "House Object",
    difficulty: 1,
  },
  {
    name: "sofa",
    icon: "🛋️",
    category: "House Object",
    difficulty: 1,
  },
  {
    name: "toilet",
    icon: "🚽",
    category: "House Object",
    difficulty: 1,
  },
  {
    name: "bed",
    icon: "🛏️",
    category: "House Object",
    difficulty: 1,
  },
  {
    name: "suitcase",
    icon: "💼",
    category: "Clothing Object",
    difficulty: 2,
  },
  {
    name: "umbrella",
    icon: "☂️",
    category: "Clothing Object",
    difficulty: 2,
  },
  {
    name: "tie",
    icon: "👔",
    category: "Clothing Object",
    difficulty: 1,
  },
  {
    name: "handbag",
    icon: "👜",
    category: "Clothing Object",
    difficulty: 2,
  },
  {
    name: "backpack",
    icon: "🎒",
    category: "Clothing Object",
    difficulty: 1,
  },
  {
    name: "boat",
    icon: "⛵",
    category: "Public Transport",
    difficulty: 10,
  },
  {
    name: "train",
    icon: "🚂",
    category: "Public Transport",
    difficulty: 10,
  },
  {
    name: "bus",
    icon: "🚌",
    category: "Public Transport",
    difficulty: 3,
  },
  {
    name: "aeroplane",
    icon: "🛩️",
    category: "Public Transport",
    difficulty: 10,
  },
  {
    name: "truck",
    icon: "🚛",
    category: "Transport",
    difficulty: 5,
  },
  {
    name: "motorbike",
    icon: "🛵",
    category: "Transport",
    difficulty: 6,
  },
  {
    name: "car",
    icon: "🚘",
    category: "Transport",
    difficulty: 1,
  },
  {
    name: "bicycle",
    icon: "🚲",
    category: "Transport",
    difficulty: 1,
  },
  {
    name: "giraffe",
    icon: "🦒",
    category: "Wild Entity",
    difficulty: 10,
  },
  {
    name: "zebra",
    icon: "🦓",
    category: "Wild Entity",
    difficulty: 10,
  },
  {
    name: "bear",
    icon: "🐻",
    category: "Wild Entity",
    difficulty: 9,
  },
  {
    name: "elephant",
    icon: "🐘",
    category: "Wild Entity",
    difficulty: 10,
  },
  {
    name: "cow",
    icon: "🐮",
    category: "Farm Entity",
    difficulty: 7,
  },
  {
    name: "sheep",
    icon: "🐑",
    category: "Farm Entity",
    difficulty: 7,
  },
  {
    name: "horse",
    icon: "🐴",
    category: "Farm Entity",
    difficulty: 8,
  },
  {
    name: "person",
    icon: "👤",
    category: "House Entity",
    difficulty: 1,
  },
  {
    name: "bird",
    icon: "🕊️",
    category: "House Entity",
    difficulty: 2,
  },
  {
    name: "cat",
    icon: "🐱",
    category: "House Entity",
    difficulty: 1,
  },
  {
    name: "dog",
    icon: "🐶",
    category: "House Entity",
    difficulty: 1,
  },
]);

export const categories = excl("categories", () =>
  all.reduce((acc, curr) => {
    const existing = acc.get(curr.category) ?? [];
    existing.push(curr);
    acc.set(curr.category, existing);
    return acc;
  }, new Map<string, typeof all>())
);
